services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: UiW7V7Qw1H2Ahu
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  web:
    build: .
    ports:
      - "80:8080"
      - "443:4443"
    volumes:
      - ./website:/var/www/html/app
      - ./certs:/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1024M
        reservations:
          cpus: 1
          memory: 512M